name: publish

on: 
  push

env:
  SERVER_NAME: lunchmoney

jobs:
  publish-server-image:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build the ${{ env.SERVER_NAME }}-server image
          run: echo "docker build . --tag ghcr.io/dylanmazurek/$SERVER_NAME-server:latest"
        - name: Push the ${{ env.SERVER_NAME }}-server image
          run: echo "docker push ghcr.io/dylanmazurek/$SERVER_NAME-server:latest"